// <auto-generated />
using Livro.Infra.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Livro.Infra.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202034907_FixRelatorioViewAssuntos")]
    partial class FixRelatorioViewAssuntos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Livro.Domain.Models.RelatorioLivro", b =>
                {
                    b.Property<string>("AnoPublicacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assuntos")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodAu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Edicao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Editora")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeTiposCompra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView("vw_RelatorioLivros", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.AssuntoEntity", b =>
                {
                    b.Property<string>("CodAs")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodAs");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CodAs");

                    b.ToTable("Assunto", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.AutorEntity", b =>
                {
                    b.Property<string>("CodAu")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodAu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("CodAu");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroAssuntoEntity", b =>
                {
                    b.Property<string>("Livro_Codl")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Livro_Codl");

                    b.Property<string>("Assunto_CodAs")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Assunto_CodAs");

                    b.HasKey("Livro_Codl", "Assunto_CodAs");

                    b.HasIndex("Assunto_CodAs");

                    b.ToTable("Livro_Assunto", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroAutorEntity", b =>
                {
                    b.Property<string>("Livro_Codl")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Livro_Codl");

                    b.Property<string>("Autor_CodAu")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Autor_CodAu");

                    b.HasKey("Livro_Codl", "Autor_CodAu");

                    b.HasIndex("Autor_CodAu");

                    b.ToTable("Livro_Autor", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroEntity", b =>
                {
                    b.Property<string>("Codl")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Codl");

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Edicao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Codl");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroValorEntity", b =>
                {
                    b.Property<string>("Codlv")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Codlv");

                    b.Property<string>("Livro_Codl")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("Livro_Codl");

                    b.Property<string>("TipoCompra_CodTc")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("TipoCompra_CodTc");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codlv");

                    b.HasIndex("Livro_Codl");

                    b.HasIndex("TipoCompra_CodTc");

                    b.ToTable("Livro_Valor", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.TipoCompraEntity", b =>
                {
                    b.Property<string>("CodTc")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodTc");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CodTc");

                    b.ToTable("TipoCompra", (string)null);
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroAssuntoEntity", b =>
                {
                    b.HasOne("Livro.Infra.EfCore.Entities.AssuntoEntity", "Assunto")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("Assunto_CodAs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livro.Infra.EfCore.Entities.LivroEntity", "Livro")
                        .WithMany("LivroAssuntos")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroAutorEntity", b =>
                {
                    b.HasOne("Livro.Infra.EfCore.Entities.AutorEntity", "Autor")
                        .WithMany("LivroAutores")
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livro.Infra.EfCore.Entities.LivroEntity", "Livro")
                        .WithMany("LivroAutores")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroValorEntity", b =>
                {
                    b.HasOne("Livro.Infra.EfCore.Entities.LivroEntity", "Livro")
                        .WithMany("LivroValores")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livro.Infra.EfCore.Entities.TipoCompraEntity", "TipoCompra")
                        .WithMany("LivroValores")
                        .HasForeignKey("TipoCompra_CodTc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("TipoCompra");
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.AssuntoEntity", b =>
                {
                    b.Navigation("LivroAssuntos");
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.AutorEntity", b =>
                {
                    b.Navigation("LivroAutores");
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.LivroEntity", b =>
                {
                    b.Navigation("LivroAssuntos");

                    b.Navigation("LivroAutores");

                    b.Navigation("LivroValores");
                });

            modelBuilder.Entity("Livro.Infra.EfCore.Entities.TipoCompraEntity", b =>
                {
                    b.Navigation("LivroValores");
                });
#pragma warning restore 612, 618
        }
    }
}
